//! Identity-keyed incremental semantics — Phase 1 + 2 of
//! `identity_keyed_semantics_plan.md`.
//!
//! This is the demonstrator for the claim that a *sound, identity-stable*
//! incremental parse lets a semantic pass reuse its own cached results for the
//! parts of the program that did not change — so per-edit semantic work scales
//! with the changed region, not the whole file.
//!
//! The semantic pass here is `eval`: a total integer interpretation of the
//! expression grammar (Phase 2, context-free — no names/scopes; the
//! context-dependent case is Phase 3). It is memoized on [`NodeId`]:
//!
//!   * A subtree the incremental parser reused keeps its `NodeId` (Clone copies
//!     `id` through the `Arc::make_mut` that restamps `stop_lbp`), so its
//!     memoized value is a hit and the evaluator does **not** even visit its
//!     children — O(1) per reused subtree.
//!   * A freshly-parsed node has a new `NodeId`, so it misses and is computed.
//!
//! **No eviction is needed for correctness.** Ids are monotonic, so a stale
//! memo entry can never collide with a new node, and reuse soundness (Paper 1
//! §2) guarantees a reused subtree has the same structure a fresh parse would
//! produce — hence the same value. `memo[id]` is therefore always consistent.
//! (Bounded-memory eviction via the reparse change-set is a separate concern,
//! noted in the plan; it does not affect the values or the recompute counts
//! this module reports.)
//!
//! Requires the `node_id` feature (this module is compiled only then).

use std::sync::Arc;

use rustc_hash::{FxHashMap, FxHashSet};

use crate::ast::{Node, NodeId, NodeKind};
use crate::lexer::TokenKind;

/// Don't bother GC-ing memos smaller than this (avoids O(n) walks on tiny
/// trees, where the leak is negligible anyway).
const GC_FLOOR: usize = 1024;

/// Total integer interpretation of one node *given its children's values*.
/// Panic-free (wrapping arithmetic; division/remainder by zero and `i64::MIN /
/// -1` yield 0). Pure: depends only on `kind` and the child values, never on
/// reuse metadata — which is why a reused subtree's restamped `stop_lbp` does
/// not affect its value.
fn combine(kind: &NodeKind, child_vals: &ChildVals) -> i64 {
    match kind {
        NodeKind::Atom(s) => s.parse::<i64>().unwrap_or(0),
        NodeKind::Prefix { op, .. } => {
            let c = child_vals.unary();
            match op {
                TokenKind::Minus => c.wrapping_neg(),
                TokenKind::Bang => (c == 0) as i64,
                _ => c,
            }
        }
        NodeKind::Binary { op, .. } => {
            let (a, b) = child_vals.binary();
            match op {
                TokenKind::Plus => a.wrapping_add(b),
                TokenKind::Minus => a.wrapping_sub(b),
                TokenKind::Star => a.wrapping_mul(b),
                TokenKind::Slash => a.checked_div(b).unwrap_or(0),
                TokenKind::Percent => a.checked_rem(b).unwrap_or(0),
                TokenKind::Caret => ipow(a, b),
                TokenKind::AndAnd => ((a != 0) && (b != 0)) as i64,
                TokenKind::OrOr => ((a != 0) || (b != 0)) as i64,
                TokenKind::EqEq => (a == b) as i64,
                TokenKind::BangEq => (a != b) as i64,
                TokenKind::Lt => (a < b) as i64,
                TokenKind::Gt => (a > b) as i64,
                TokenKind::LtEq => (a <= b) as i64,
                TokenKind::GtEq => (a >= b) as i64,
                _ => 0,
            }
        }
        NodeKind::Ternary { .. } => {
            let (c, t, e) = child_vals.ternary();
            if c != 0 {
                t
            } else {
                e
            }
        }
        NodeKind::Paren { .. } => child_vals.unary(),
        // Postfix forms are not generated by the Phase 2 (arithmetic) inputs;
        // defined totally so `eval` never panics on an arbitrary tree.
        NodeKind::Call { .. } => child_vals.first(),
        NodeKind::Index { .. } => child_vals.first().wrapping_add(child_vals.nth(1)),
        NodeKind::Member { .. } => child_vals.first(),
        NodeKind::Missing | NodeKind::Error { .. } => 0,
    }
}

/// `a ** b` for non-negative `b`, wrapping; `0` for negative exponent.
/// `O(log b)` iterations, no panic.
fn ipow(a: i64, b: i64) -> i64 {
    if b < 0 {
        return 0;
    }
    let mut result: i64 = 1;
    let mut base = a;
    let mut e = b as u64;
    while e > 0 {
        if e & 1 == 1 {
            result = result.wrapping_mul(base);
        }
        base = base.wrapping_mul(base);
        e >>= 1;
    }
    result
}

/// Collected child values for `combine`, in parse order.
struct ChildVals(Vec<i64>);
impl ChildVals {
    fn first(&self) -> i64 {
        self.0.first().copied().unwrap_or(0)
    }
    fn nth(&self, i: usize) -> i64 {
        self.0.get(i).copied().unwrap_or(0)
    }
    fn unary(&self) -> i64 {
        self.first()
    }
    fn binary(&self) -> (i64, i64) {
        (self.nth(0), self.nth(1))
    }
    fn ternary(&self) -> (i64, i64, i64) {
        (self.nth(0), self.nth(1), self.nth(2))
    }
}

/// A memoizing evaluator keyed on [`NodeId`]. Hold one across edits: feed it
/// the old tree, then each reparsed tree; unchanged subtrees are served from
/// the memo at O(1) and their interiors are never revisited.
#[derive(Default)]
pub struct IncrementalEvaluator {
    memo: FxHashMap<NodeId, i64>,
    /// Reachability-GC trigger: when `memo.len()` exceeds this, drop entries
    /// for nodes no longer in the live tree (see `eval`). 0 = not yet set.
    gc_threshold: usize,
    /// Nodes whose value was computed during the most recent `eval` (memo
    /// misses) — i.e. genuinely fresh work.
    pub recomputed: usize,
    /// Subtrees served from the memo during the most recent `eval` (top-level
    /// reuse events; their interiors are not visited).
    pub reused: usize,
}

impl IncrementalEvaluator {
    pub fn new() -> Self {
        Self::default()
    }

    /// Evaluate `root`, reusing memoized values for any subtree whose `NodeId`
    /// is already known. Resets and reports `recomputed`/`reused` for this call.
    ///
    /// Memo memory is bounded by a reachability GC: since ids are monotonic,
    /// stale entries (nodes from previous trees no longer present) are never
    /// false hits but would leak across a long edit session. When the memo
    /// outgrows its threshold we retain only entries reachable from the current
    /// `root` and reset the threshold to 2× the live size. The check is O(1) per
    /// edit; the GC walk is O(n) but rare (garbage accrues ~O(edit) per edit, so
    /// GCs are ~O(n/edit) apart → amortized small) and perf-neutral (it keeps
    /// every live entry, so nothing useful is evicted).
    pub fn eval(&mut self, root: &Arc<Node>) -> i64 {
        self.recomputed = 0;
        self.reused = 0;
        let v = self.eval_node(root);
        if self.memo.len() > self.gc_threshold.max(GC_FLOOR) {
            let mut live = FxHashSet::default();
            collect_reachable(root, &mut live);
            self.memo.retain(|k, _| live.contains(k));
            self.gc_threshold = self.memo.len() * 2;
        }
        v
    }

    fn eval_node(&mut self, n: &Arc<Node>) -> i64 {
        if let Some(&v) = self.memo.get(&n.id) {
            self.reused += 1;
            return v;
        }
        self.recomputed += 1;
        // Evaluate children first (in parse order), then combine.
        let mut vals = Vec::new();
        for_each_child(&n.kind, &mut |c| vals.push(self.eval_node(c)));
        let v = combine(&n.kind, &ChildVals(vals));
        self.memo.insert(n.id, v);
        v
    }

    /// Number of distinct nodes whose value is currently memoized.
    pub fn memo_len(&self) -> usize {
        self.memo.len()
    }
}

/// Non-memoizing reference evaluation (the from-scratch oracle). Equivalent to
/// `IncrementalEvaluator::new().eval(root)` but makes intent explicit in tests.
pub fn eval_fresh(root: &Arc<Node>) -> i64 {
    IncrementalEvaluator::new().eval(root)
}

/// Collect every node id reachable from `root` (full O(n) walk). Used by the
/// reachability GC to find the live set.
fn collect_reachable(node: &Arc<Node>, out: &mut FxHashSet<NodeId>) {
    out.insert(node.id);
    for_each_child(&node.kind, &mut |c| collect_reachable(c, out));
}

/// Visit a node's children in parse order. Centralizes the child structure so
/// `eval_node` and any future pass share one definition.
fn for_each_child<'a>(kind: &'a NodeKind, f: &mut dyn FnMut(&'a Arc<Node>)) {
    match kind {
        NodeKind::Atom(_) | NodeKind::Missing | NodeKind::Error { .. } => {}
        NodeKind::Prefix { child, .. } => f(child),
        NodeKind::Binary { left, right, .. } => {
            f(left);
            f(right);
        }
        NodeKind::Ternary { cond, then, else_ } => {
            f(cond);
            f(then);
            f(else_);
        }
        NodeKind::Paren { inner } => f(inner),
        NodeKind::Call { callee, args } => {
            f(callee);
            for a in args {
                f(a);
            }
        }
        NodeKind::Index { array, index } => {
            f(array);
            f(index);
        }
        NodeKind::Member { object, .. } => f(object),
    }
}
